### ISSUE TITLE
code typo 

### ISSUE THREAD

**Issue by progamer71** [cbergoon/merkletree#15]
There is a typo in line 127 of merkle_tree.go.
https://github.com/cbergoon/merkletree/blob/master/merkle_tree.go#L127

code
```
if bytes.Equal(currentParent.Left.Hash, current.Hash) {
```
should be
```
if bytes.Equal(currentParent.Right.Hash, current.Hash) {
```

(sorry I cannot make a pull request)

**Comment by cbergoon** [comment]
Hi @progamer71 

The idea of the merkle proof path is that the *missing* hashes of the nodes that are required to prove a leafs membership to the tree are provided as a result. Essentially providing the information required to verify the merkle root without having the entire tree. Given this intent, I think the current implementation is correct. 

There is a good StackExchange answer explaining this concept: https://bitcoin.stackexchange.com/a/50680

Cam

**Comment by progamer71** [comment]
sorry I just got it. your are correct.
