### ISSUE TITLE
Useless parameter in VerifyContent

### ISSUE THREAD

**Issue by buraksezer** [cbergoon/merkletree#3]
Hello,

`expectedMerkleRoot` parameter is unused in the code. 

https://github.com/cbergoon/merkletree/blob/0e68ec9a138d919b3052ba7cfea5f0a63630cdfe/merkle_tree.go#L179

**Comment by bingqianglin** [comment]
also .

**Comment by cbergoon** [comment]
Removed this parameter in 05d5987. 

Thanks for the issue!
Cam
