### ISSUE TITLE
Unhandled err

### ISSUE THREAD

**Issue by adam-hanna** [cbergoon/merkletree#4]
https://github.com/cbergoon/merkletree/blob/0e68ec9a138d919b3052ba7cfea5f0a63630cdfe/merkle_tree.go#L47

The [hash writer](https://golang.org/pkg/hash/#Hash) is an [io.Writer](https://golang.org/pkg/io/#Writer). The write method of the io.Writer returns the number of bytes written and an error: `Write(p []byte) (n int, err error)`. These errors are not being handled in your code when you do `h.Write(...)`

I would suggest changing all instances of `h.Write(...)` to:
```go
if _, err := h.Write(...); err != nil {
  return .., err
}
```

**Comment by cbergoon** [comment]
I agree, and I see you you already made a PR. 

Thanks! 

Cam
