### ISSUE TITLE
Allow a configurable hash function

### ISSUE THREAD

**Issue by absfox** [cbergoon/merkletree#9]
I was wondering if you would be open to supporting a configurable hash function.  

In other words pass the hash function as an argument along with the content list when building the tree. Something like:

`merkle.NewTree(list, sha256.New)`

**Comment by cbergoon** [comment]
Sounds like a great idea. I'd like to preserve the original API and create a new "New" function (e.g. `NewTreeWithHashStrategy(list, sha256.New)`). The original `NewTree(list)` function could set the default to the hash function that is currently used. 

Cam

**Comment by cbergoon** [comment]
@absfox 

I added the below function to allow the hash function to be configurable. 

`func NewTreeWithHashStrategy(cs []Content, hashStrategy func() hash.Hash) (*MerkleTree, error)`

The default hash remains sha256.
